// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EngenhariaReversa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EngenhariaReversa.Models.Configurations
{
    public partial class PedidoItemConfiguration : IEntityTypeConfiguration<PedidoItem>
    {
        public void Configure(EntityTypeBuilder<PedidoItem> entity)
        {
            entity.HasKey(e => new { e.PedidoId, e.ProdutoId });

            entity.HasIndex(e => e.ProdutoId, "IX_PedidoItem_ProdutoId");

            entity.Property(e => e.Quantidade).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.Valor).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Pedido)
                .WithMany(p => p.PedidoItem)
                .HasForeignKey(d => d.PedidoId);

            entity.HasOne(d => d.Produto)
                .WithMany(p => p.PedidoItem)
                .HasForeignKey(d => d.ProdutoId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PedidoItem> entity);
    }
}
