// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EngenhariaReversa.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace EngenhariaReversa.Models.Configurations
{
    public partial class ProdutoConfiguration : IEntityTypeConfiguration<Produto>
    {
        public void Configure(EntityTypeBuilder<Produto> entity)
        {
            entity.Property(e => e.Nome).HasMaxLength(100);

            entity.Property(e => e.Valor).HasColumnType("decimal(18, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Produto> entity);
    }
}
