// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EngenhariaReversa.Models.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
#nullable enable

namespace EngenhariaReversa.Models
{
    public partial class EF1Context : DbContext
    {
        public EF1Context(DbContextOptions<EF1Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Cliente { get; set; } = null!;
        public virtual DbSet<Pedido> Pedido { get; set; } = null!;
        public virtual DbSet<PedidoItem> PedidoItem { get; set; } = null!;
        public virtual DbSet<Produto> Produto { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.ClienteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PedidoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PedidoItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProdutoConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
