// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EngenhariaReversa.Models
{
    public partial class Produto
    {
        public Produto()
        {
            PedidoItem = new HashSet<PedidoItem>();
        }

        public int Id { get; set; }
        public string Nome { get; set; } = null!;
        public decimal Valor { get; set; }

        public virtual ICollection<PedidoItem> PedidoItem { get; set; }
    }
}